-- CHECK CONSTRAINT TRẠNG THÁI
USE HAPPYPET
GO

-- Xem constraint hiện tại
SELECT 
    tc.CONSTRAINT_NAME,
    cc.CHECK_CLAUSE,
    tc.TABLE_NAME,
    ccu.COLUMN_NAME
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS tc
JOIN INFORMATION_SCHEMA.CHECK_CONSTRAINTS cc ON tc.CONSTRAINT_NAME = cc.CONSTRAINT_NAME
JOIN INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE ccu ON tc.CONSTRAINT_NAME = ccu.CONSTRAINT_NAME
WHERE tc.TABLE_NAME = 'PHIEU_DICH_VU'
  AND ccu.COLUMN_NAME = 'TrangThai';

-- Xem tất cả giá trị TrangThai đang có trong database
SELECT DISTINCT TrangThai, COUNT(*) AS SoLuong
FROM PHIEU_DICH_VU
GROUP BY TrangThai
ORDER BY TrangThai;
