USE HAPPYPET
GO

INSERT INTO DV_CN (MaCN, MaLoaiDV) VALUES (N'CN01', N'DV02');
INSERT INTO DV_CN (MaCN, MaLoaiDV) VALUES (N'CN01', N'DV01');
INSERT INTO DV_CN (MaCN, MaLoaiDV) VALUES (N'CN01', N'DV03');
INSERT INTO DV_CN (MaCN, MaLoaiDV) VALUES (N'CN02', N'DV02');
INSERT INTO DV_CN (MaCN, MaLoaiDV) VALUES (N'CN02', N'DV01');
INSERT INTO DV_CN (MaCN, MaLoaiDV) VALUES (N'CN03', N'DV02');
INSERT INTO DV_CN (MaCN, MaLoaiDV) VALUES (N'CN03', N'DV03');
INSERT INTO DV_CN (MaCN, MaLoaiDV) VALUES (N'CN04', N'DV03');
INSERT INTO DV_CN (MaCN, MaLoaiDV) VALUES (N'CN04', N'DV02');
INSERT INTO DV_CN (MaCN, MaLoaiDV) VALUES (N'CN04', N'DV01');
INSERT INTO DV_CN (MaCN, MaLoaiDV) VALUES (N'CN05', N'DV01');
INSERT INTO DV_CN (MaCN, MaLoaiDV) VALUES (N'CN05', N'DV03');
INSERT INTO DV_CN (MaCN, MaLoaiDV) VALUES (N'CN06', N'DV03');
INSERT INTO DV_CN (MaCN, MaLoaiDV) VALUES (N'CN06', N'DV02');
INSERT INTO DV_CN (MaCN, MaLoaiDV) VALUES (N'CN06', N'DV01');
INSERT INTO DV_CN (MaCN, MaLoaiDV) VALUES (N'CN07', N'DV03');
INSERT INTO DV_CN (MaCN, MaLoaiDV) VALUES (N'CN07', N'DV01');
INSERT INTO DV_CN (MaCN, MaLoaiDV) VALUES (N'CN07', N'DV02');
INSERT INTO DV_CN (MaCN, MaLoaiDV) VALUES (N'CN08', N'DV02');
INSERT INTO DV_CN (MaCN, MaLoaiDV) VALUES (N'CN08', N'DV03');
INSERT INTO DV_CN (MaCN, MaLoaiDV) VALUES (N'CN09', N'DV01');
INSERT INTO DV_CN (MaCN, MaLoaiDV) VALUES (N'CN09', N'DV03');
INSERT INTO DV_CN (MaCN, MaLoaiDV) VALUES (N'CN09', N'DV02');
INSERT INTO DV_CN (MaCN, MaLoaiDV) VALUES (N'CN10', N'DV01');
INSERT INTO DV_CN (MaCN, MaLoaiDV) VALUES (N'CN10', N'DV03');
INSERT INTO DV_CN (MaCN, MaLoaiDV) VALUES (N'CN10', N'DV02');