USE HAPPYPET
GO

INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0001', N'Run rẩy hoặc co giật cơ bắp (cần theo dõi nghiêm ngặt).', N'Thuốc mỡ', N'Không cần kê đơn', 140000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0002', N'Run rẩy hoặc co giật cơ bắp (cần theo dõi nghiêm ngặt).', N'Viên nén', N'Không cần kê đơn', 260000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0003', N'Gây khó chịu nhẹ ở dạ dày nếu dùng lúc đói.', N'Thuốc bột pha dung dịch', N'Không cần kê đơn', 290000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0004', N'Không có tác dụng phụ đáng kể.', N'Viên nén', N'Cần kê đơn', 270000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0005', N'Tiêu chảy hoặc phân lỏng tạm thời, nên dùng kèm thức ăn.', N'Viên nén', N'Cần kê đơn', 130000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0006', N'Kích ứng da hoặc niêm mạc (tại chỗ bôi/tiêm).', N'Thuốc mỡ', N'Không cần kê đơn', 110000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0007', N'Có thể gây vàng da, cần theo dõi chức năng gan.', N'Dung dịch nhỏ mắt/tai', N'Không cần kê đơn', 480000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0008', N'Mất cân bằng, đi lại loạng choạng sau khi dùng thuốc.', N'Dung dịch nhỏ mắt/tai', N'Cần kê đơn', 180000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0009', N'Không có tác dụng phụ đáng kể.', N'Thuốc mỡ', N'Cần kê đơn', 140000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0010', N'Buồn ngủ nhẹ hoặc lừ đừ (phổ biến).', N'Thuốc mỡ', N'Không cần kê đơn', 430000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0011', N'Khó thở nhẹ, thở nhanh.', N'Siro', N'Cần kê đơn', 90000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0012', N'Mất cân bằng, đi lại loạng choạng sau khi dùng thuốc.', N'Thuốc mỡ', N'Cần kê đơn', 140000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0013', N'Tăng cường cảm giác thèm ăn hoặc ngược lại, biếng ăn thoáng qua.', N'Thuốc mỡ', N'Cần kê đơn', 280000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0014', N'Thay đổi hành vi: kích động, bồn chồn hoặc lo lắng.', N'Thuốc tiêm', N'Không cần kê đơn', 230000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0015', N'Khó thở nhẹ, thở nhanh.', N'Thuốc tiêm', N'Cần kê đơn', 290000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0016', N'Uống nhiều nước và tiểu tiện nhiều hơn bình thường.', N'Thuốc bột pha dung dịch', N'Không cần kê đơn', 290000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0017', N'Có thể gây vàng da, cần theo dõi chức năng gan.', N'Dung dịch nhỏ mắt/tai', N'Cần kê đơn', 130000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0018', N'Kích ứng da hoặc niêm mạc (tại chỗ bôi/tiêm).', N'Dung dịch nhỏ mắt/tai', N'Không cần kê đơn', 100000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0019', N'Có thể gây vàng da, cần theo dõi chức năng gan.', N'Thuốc mỡ', N'Cần kê đơn', 400000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0020', N'Nôn mửa hoặc sùi bọt mép .', N'Thuốc mỡ', N'Không cần kê đơn', 50000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0021', N'Uống nhiều nước và tiểu tiện nhiều hơn bình thường.', N'Thuốc tiêm', N'Không cần kê đơn', 230000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0022', N'Uống nhiều nước và tiểu tiện nhiều hơn bình thường.', N'Thuốc mỡ', N'Cần kê đơn', 330000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0023', N'Buồn ngủ nhẹ hoặc lừ đừ (phổ biến).', N'Viên nén', N'Không cần kê đơn', 250000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0024', N'Kích ứng da hoặc niêm mạc (tại chỗ bôi/tiêm).', N'Viên nén', N'Cần kê đơn', 140000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0025', N'Tổn thương niêm mạc dạ dày nếu dùng liều cao kéo dài.', N'Viên nén', N'Cần kê đơn', 300000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0026', N'Có thể gây vàng da, cần theo dõi chức năng gan.', N'Viên nang mềm', N'Cần kê đơn', 260000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0027', N'Thay đổi hành vi: kích động, bồn chồn hoặc lo lắng.', N'Viên nang mềm', N'Không cần kê đơn', 290000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0028', N'Uống nhiều nước và tiểu tiện nhiều hơn bình thường.', N'Thuốc tiêm', N'Không cần kê đơn', 480000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0029', N'Tiêu chảy hoặc phân lỏng tạm thời, nên dùng kèm thức ăn.', N'Viên nén', N'Không cần kê đơn', 160000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0030', N'Không có tác dụng phụ đáng kể.', N'Dung dịch nhỏ mắt/tai', N'Cần kê đơn', 50000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0031', N'Không có tác dụng phụ đáng kể.', N'Viên nang mềm (Softgel)', N'Cần kê đơn', 400000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0032', N'Khó thở nhẹ, thở nhanh.', N'Viên nén (Tablet)', N'Không cần kê đơn', 220000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0033', N'Tiêu chảy hoặc phân lỏng tạm thời, nên dùng kèm thức ăn.', N'Viên nang mềm (Softgel)', N'Cần kê đơn', 60000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0034', N'Kích ứng da hoặc niêm mạc (tại chỗ bôi/tiêm).', N'Viên nang mềm (Softgel)', N'Không cần kê đơn', 370000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0035', N'Kích ứng da hoặc niêm mạc (tại chỗ bôi/tiêm).', N'Viên nang mềm (Softgel)', N'Cần kê đơn', 100000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0036', N'Có thể gây vàng da, cần theo dõi chức năng gan.', N'Viên nang mềm (Softgel)', N'Cần kê đơn', 150000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0037', N'Khó thở nhẹ, thở nhanh.', N'Thuốc tiêm', N'Không cần kê đơn', 280000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0038', N'Kích ứng da hoặc niêm mạc (tại chỗ bôi/tiêm).', N'Thuốc mỡ', N'Không cần kê đơn', 300000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0039', N'Có thể gây vàng da, cần theo dõi chức năng gan.', N'Viên nang mềm (Softgel)', N'Không cần kê đơn', 70000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0040', N'Uống nhiều nước và tiểu tiện nhiều hơn bình thường.', N'Viên nén (Tablet)', N'Cần kê đơn', 230000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0041', N'Kích ứng da hoặc niêm mạc (tại chỗ bôi/tiêm).', N'Thuốc mỡ', N'Không cần kê đơn', 270000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0042', N'Buồn ngủ nhẹ hoặc lừ đừ (phổ biến).', N'Thuốc bột pha dung dịch', N'Cần kê đơn', 90000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0043', N'Không có tác dụng phụ đáng kể.', N'Siro', N'Không cần kê đơn', 250000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0044', N'Mất cân bằng, đi lại loạng choạng sau khi dùng thuốc.', N'Viên nang mềm', N'Không cần kê đơn', 230000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0045', N'Không có tác dụng phụ đáng kể.', N'Viên nang mềm', N'Không cần kê đơn', 260000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0046', N'Nôn mửa hoặc sùi bọt mép .', N'Dung dịch nhỏ mắt/tai', N'Cần kê đơn', 190000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0047', N'Khó thở nhẹ, thở nhanh.', N'Thuốc tiêm', N'Cần kê đơn', 160000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0048', N'Tiêu chảy hoặc phân lỏng tạm thời, nên dùng kèm thức ăn.', N'Thuốc tiêm', N'Không cần kê đơn', 120000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0049', N'Khó thở nhẹ, thở nhanh.', N'Thuốc bột pha dung dịch', N'Cần kê đơn', 470000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0050', N'Run rẩy hoặc co giật cơ bắp (cần theo dõi nghiêm ngặt).', N'Siro', N'Cần kê đơn', 150000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0051', N'Kích ứng da hoặc niêm mạc (tại chỗ bôi/tiêm).', N'Viên nén', N'Không cần kê đơn', 50000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0052', N'Tiêu chảy hoặc phân lỏng tạm thời, nên dùng kèm thức ăn.', N'Thuốc tiêm', N'Cần kê đơn', 340000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0053', N'Gây nhạy cảm ánh sáng (nên tránh nắng).', N'Thuốc tiêm', N'Cần kê đơn', 210000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0054', N'Có thể gây vàng da, cần theo dõi chức năng gan.', N'Viên nén', N'Không cần kê đơn', 100000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0055', N'Run rẩy hoặc co giật cơ bắp (cần theo dõi nghiêm ngặt).', N'Siro', N'Cần kê đơn', 390000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0056', N'Có thể gây vàng da, cần theo dõi chức năng gan.', N'Thuốc tiêm', N'Cần kê đơn', 170000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0057', N'Tăng cường cảm giác thèm ăn hoặc ngược lại, biếng ăn thoáng qua.', N'Thuốc mỡ', N'Cần kê đơn', 170000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0058', N'Có thể gây vàng da, cần theo dõi chức năng gan.', N'Thuốc mỡ', N'Cần kê đơn', 380000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0059', N'Run rẩy hoặc co giật cơ bắp (cần theo dõi nghiêm ngặt).', N'Viên nén', N'Cần kê đơn', 100000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0060', N'Thay đổi hành vi: kích động, bồn chồn hoặc lo lắng.', N'Thuốc tiêm', N'Cần kê đơn', 300000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0061', N'Kích ứng da hoặc niêm mạc (tại chỗ bôi/tiêm).', N'Siro', N'Không cần kê đơn', 230000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0062', N'Tăng cường cảm giác thèm ăn hoặc ngược lại, biếng ăn thoáng qua.', N'Thuốc bột pha dung dịch', N'Cần kê đơn', 100000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0063', N'Mất cân bằng, đi lại loạng choạng sau khi dùng thuốc.', N'Viên nang mềm', N'Cần kê đơn', 240000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0064', N'Khó thở nhẹ, thở nhanh.', N'Dung dịch nhỏ mắt/tai', N'Cần kê đơn', 500000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0065', N'Kích ứng nhẹ, đỏ da (tại chỗ).', N'Thuốc mỡ', N'Không cần kê đơn', 180000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0066', N'Không có tác dụng phụ đáng kể.', N'Dung dịch nhỏ mắt/tai', N'Không cần kê đơn', 50000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0067', N'Thay đổi hành vi: kích động, bồn chồn hoặc lo lắng.', N'Dung dịch nhỏ mắt/tai', N'Không cần kê đơn', 300000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0068', N'Tăng cường cảm giác thèm ăn hoặc ngược lại, biếng ăn thoáng qua.', N'Viên nén', N'Không cần kê đơn', 100000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0069', N'Không có tác dụng phụ đáng kể.', N'Thuốc tiêm', N'Cần kê đơn', 290000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0070', N'Nôn mửa hoặc sùi bọt mép .', N'Viên nén', N'Không cần kê đơn', 330000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0071', N'Uống nhiều nước và tiểu tiện nhiều hơn bình thường.', N'Siro', N'Cần kê đơn', 100000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0072', N'Khó thở nhẹ, thở nhanh.', N'Viên nang mềm', N'Cần kê đơn', 160000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0073', N'Run rẩy hoặc co giật cơ bắp (cần theo dõi nghiêm ngặt).', N'Viên nang mềm', N'Không cần kê đơn', 440000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0074', N'Run rẩy hoặc co giật cơ bắp (cần theo dõi nghiêm ngặt).', N'Thuốc tiêm', N'Cần kê đơn', 80000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0075', N'Mất cân bằng, đi lại loạng choạng sau khi dùng thuốc.', N'Siro', N'Không cần kê đơn', 70000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0076', N'Tiêu chảy hoặc phân lỏng tạm thời, nên dùng kèm thức ăn.', N'Viên nén', N'Cần kê đơn', 440000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0077', N'Buồn ngủ nhẹ hoặc lừ đừ (phổ biến).', N'Siro', N'Cần kê đơn', 180000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0078', N'Tổn thương thần kinh trung ương nếu dùng quá liều.', N'Thuốc tiêm', N'Cần kê đơn', 300000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0079', N'Buồn ngủ nhẹ hoặc lừ đừ (phổ biến).', N'Thuốc tiêm', N'Không cần kê đơn', 140000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0080', N'Tiêu chảy hoặc phân lỏng tạm thời, nên dùng kèm thức ăn.', N'Thuốc mỡ', N'Không cần kê đơn', 110000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0081', N'Run rẩy hoặc co giật cơ bắp (cần theo dõi nghiêm ngặt).', N'Thuốc bột pha dung dịch', N'Không cần kê đơn', 290000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0082', N'Nôn mửa hoặc sùi bọt mép .', N'Viên nén', N'Không cần kê đơn', 150000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0083', N'Uống nhiều nước và tiểu tiện nhiều hơn bình thường.', N'Viên nang mềm', N'Cần kê đơn', 230000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0084', N'Khó thở nhẹ, thở nhanh.', N'Viên nang mềm', N'Cần kê đơn', 120000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0085', N'Khó thở nhẹ, thở nhanh.', N'Siro', N'Không cần kê đơn', 240000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0086', N'Không có tác dụng phụ đáng kể.', N'Siro', N'Cần kê đơn', 270000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0087', N'Nôn mửa hoặc sùi bọt mép .', N'Thuốc tiêm', N'Cần kê đơn', 50000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0088', N'Uống nhiều nước và tiểu tiện nhiều hơn bình thường.', N'Thuốc tiêm', N'Không cần kê đơn', 280000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0089', N'Tiêu chảy hoặc phân lỏng tạm thời, nên dùng kèm thức ăn.', N'Dung dịch nhỏ mắt/tai', N'Cần kê đơn', 270000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0090', N'Tăng cường cảm giác thèm ăn hoặc ngược lại, biếng ăn thoáng qua.', N'Viên nén', N'Không cần kê đơn', 290000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0091', N'Thay đổi hành vi: kích động, bồn chồn hoặc lo lắng.', N'Siro', N'Không cần kê đơn', 220000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0092', N'Uống nhiều nước và tiểu tiện nhiều hơn bình thường.', N'Thuốc bột pha dung dịch', N'Cần kê đơn', 220000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0093', N'Tăng cường cảm giác thèm ăn hoặc ngược lại, biếng ăn thoáng qua.', N'Viên nang mềm', N'Không cần kê đơn', 160000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0094', N'Kích ứng da hoặc niêm mạc (tại chỗ bôi/tiêm).', N'Dung dịch nhỏ mắt/tai', N'Cần kê đơn', 350000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0095', N'Run rẩy hoặc co giật cơ bắp (cần theo dõi nghiêm ngặt).', N'Viên nén', N'Cần kê đơn', 270000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0096', N'Tiêu chảy hoặc phân lỏng tạm thời, nên dùng kèm thức ăn.', N'Viên nén', N'Không cần kê đơn', 300000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0097', N'Buồn ngủ nhẹ hoặc lừ đừ (phổ biến).', N'Thuốc bột pha dung dịch', N'Không cần kê đơn', 180000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0098', N'Nôn mửa hoặc sùi bọt mép .', N'Thuốc bột pha dung dịch', N'Không cần kê đơn', 150000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0099', N'Mất cân bằng, đi lại loạng choạng sau khi dùng thuốc.', N'Thuốc mỡ', N'Cần kê đơn', 250000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0100', N'Run rẩy hoặc co giật cơ bắp (cần theo dõi nghiêm ngặt).', N'Dung dịch nhỏ mắt/tai', N'Không cần kê đơn', 470000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0101', N'Có thể gây vàng da, cần theo dõi chức năng gan.', N'Thuốc tiêm', N'Cần kê đơn', 100000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0102', N'Buồn ngủ nhẹ hoặc lừ đừ (phổ biến).', N'Viên nén', N'Cần kê đơn', 290000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0103', N'Mất cân bằng, đi lại loạng choạng sau khi dùng thuốc.', N'Thuốc bột pha dung dịch', N'Không cần kê đơn', 400000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0104', N'Uống nhiều nước và tiểu tiện nhiều hơn bình thường.', N'Thuốc mỡ', N'Không cần kê đơn', 140000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0105', N'Tiêu chảy hoặc phân lỏng tạm thời, nên dùng kèm thức ăn.', N'Thuốc bột pha dung dịch', N'Cần kê đơn', 240000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0106', N'Tiêu chảy hoặc phân lỏng tạm thời, nên dùng kèm thức ăn.', N'Siro', N'Cần kê đơn', 380000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0107', N'Thay đổi hành vi: kích động, bồn chồn hoặc lo lắng.', N'Siro', N'Cần kê đơn', 230000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0108', N'Khó thở nhẹ, thở nhanh.', N'Viên nang mềm', N'Cần kê đơn', 230000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0109', N'Nôn mửa hoặc sùi bọt mép .', N'Siro', N'Không cần kê đơn', 260000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0110', N'Tăng cường cảm giác thèm ăn hoặc ngược lại, biếng ăn thoáng qua.', N'Thuốc mỡ', N'Cần kê đơn', 240000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0111', N'Không có tác dụng phụ đáng kể.', N'Thuốc bột pha dung dịch', N'Không cần kê đơn', 190000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0112', N'Run rẩy hoặc co giật cơ bắp (cần theo dõi nghiêm ngặt).', N'Siro', N'Cần kê đơn', 290000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0113', N'Thay đổi hành vi: kích động, bồn chồn hoặc lo lắng.', N'Siro', N'Cần kê đơn', 220000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0114', N'Hạ huyết áp đột ngột hoặc chóng mặt.', N'Viên nén', N'Cần kê đơn', 180000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0115', N'Nôn mửa hoặc sùi bọt mép .', N'Thuốc tiêm', N'Không cần kê đơn', 130000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0116', N'Khó thở nhẹ, thở nhanh.', N'Viên nén', N'Không cần kê đơn', 100000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0117', N'Buồn ngủ nhẹ hoặc lừ đừ (phổ biến).', N'Dung dịch nhỏ mắt/tai', N'Cần kê đơn', 280000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0118', N'Không có tác dụng phụ đáng kể.', N'Dung dịch nhỏ mắt/tai', N'Không cần kê đơn', 280000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0119', N'Có thể gây vàng da, cần theo dõi chức năng gan.', N'Viên nén', N'Cần kê đơn', 140000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0120', N'Run rẩy hoặc co giật cơ bắp (cần theo dõi nghiêm ngặt).', N'Thuốc mỡ', N'Cần kê đơn', 210000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0121', N'Nôn mửa hoặc sùi bọt mép .', N'Thuốc tiêm', N'Cần kê đơn', 340000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0122', N'Tiêu chảy hoặc phân lỏng tạm thời, nên dùng kèm thức ăn.', N'Thuốc mỡ', N'Không cần kê đơn', 100000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0123', N'Uống nhiều nước và tiểu tiện nhiều hơn bình thường.', N'Dung dịch nhỏ mắt/tai', N'Cần kê đơn', 90000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0124', N'Khó thở nhẹ, thở nhanh.', N'Thuốc tiêm', N'Cần kê đơn', 240000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0125', N'Nôn mửa hoặc sùi bọt mép .', N'Thuốc mỡ', N'Cần kê đơn', 90000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0126', N'Không có tác dụng phụ đáng kể.', N'Viên nang mềm', N'Không cần kê đơn', 220000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0127', N'Có thể gây vàng da, cần theo dõi chức năng gan.', N'Siro', N'Cần kê đơn', 110000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0128', N'Buồn ngủ nhẹ hoặc lừ đừ (phổ biến).', N'Dung dịch nhỏ mắt/tai', N'Cần kê đơn', 170000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0129', N'Có thể gây vàng da, cần theo dõi chức năng gan.', N'Thuốc bột pha dung dịch', N'Cần kê đơn', 170000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0130', N'Buồn ngủ nhẹ hoặc lừ đừ (phổ biến).', N'Thuốc bột pha dung dịch', N'Không cần kê đơn', 180000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0131', N'Run rẩy hoặc co giật cơ bắp (cần theo dõi nghiêm ngặt).', N'Thuốc tiêm', N'Không cần kê đơn', 300000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0132', N'Tăng cường cảm giác thèm ăn hoặc ngược lại, biếng ăn thoáng qua.', N'Thuốc mỡ', N'Cần kê đơn', 210000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0133', N'Buồn ngủ nhẹ hoặc lừ đừ (phổ biến).', N'Viên nang mềm', N'Không cần kê đơn', 290000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0134', N'Không có tác dụng phụ đáng kể.', N'Thuốc bột pha dung dịch', N'Cần kê đơn', 200000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0135', N'Thay đổi hành vi: kích động, bồn chồn hoặc lo lắng.', N'Viên nén', N'Không cần kê đơn', 190000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0136', N'Uống nhiều nước và tiểu tiện nhiều hơn bình thường.', N'Thuốc tiêm', N'Cần kê đơn', 190000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0137', N'Uống nhiều nước và tiểu tiện nhiều hơn bình thường.', N'Viên nén', N'Cần kê đơn', 120000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0138', N'Khó thở nhẹ, thở nhanh.', N'Thuốc bột pha dung dịch', N'Cần kê đơn', 250000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0139', N'Uống nhiều nước và tiểu tiện nhiều hơn bình thường.', N'Thuốc tiêm', N'Không cần kê đơn', 210000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0140', N'Kích ứng da hoặc niêm mạc (tại chỗ bôi/tiêm).', N'Dung dịch nhỏ mắt/tai', N'Cần kê đơn', 210000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0141', N'Không có tác dụng phụ đáng kể.', N'Siro', N'Không cần kê đơn', 220000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0142', N'Kích ứng da hoặc niêm mạc (tại chỗ bôi/tiêm).', N'Dung dịch nhỏ mắt/tai', N'Không cần kê đơn', 100000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0143', N'Nôn mửa hoặc sùi bọt mép .', N'Thuốc tiêm', N'Không cần kê đơn', 140000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0144', N'Đau hoặc sưng nhẹ tại vị trí tiêm.', N'Thuốc tiêm', N'Cần kê đơn', 270000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0145', N'Nôn mửa hoặc sùi bọt mép .', N'Viên nang mềm', N'Cần kê đơn', 470000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0146', N'Không có tác dụng phụ đáng kể.', N'Viên nang mềm', N'Không cần kê đơn', 180000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0147', N'Nôn mửa hoặc sùi bọt mép .', N'Thuốc tiêm', N'Cần kê đơn', 230000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0148', N'Thay đổi hành vi: kích động, bồn chồn hoặc lo lắng.', N'Dung dịch nhỏ mắt/tai', N'Cần kê đơn', 180000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0149', N'Uống nhiều nước và tiểu tiện nhiều hơn bình thường.', N'Viên nang mềm', N'Không cần kê đơn', 100000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0150', N'Buồn ngủ nhẹ hoặc lừ đừ (phổ biến).', N'Thuốc mỡ', N'Không cần kê đơn', 300000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0151', N'Có thể gây vàng da, cần theo dõi chức năng gan.', N'Thuốc tiêm', N'Không cần kê đơn', 250000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0152', N'Tăng cường cảm giác thèm ăn hoặc ngược lại, biếng ăn thoáng qua.', N'Thuốc tiêm', N'Cần kê đơn', 250000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0153', N'Tiêu chảy hoặc phân lỏng tạm thời, nên dùng kèm thức ăn.', N'Thuốc mỡ', N'Cần kê đơn', 140000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0154', N'Nôn mửa hoặc sùi bọt mép .', N'Thuốc mỡ', N'Cần kê đơn', 270000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0155', N'Không có tác dụng phụ đáng kể.', N'Thuốc bột pha dung dịch', N'Không cần kê đơn', 100000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0156', N'Thay đổi hành vi: kích động, bồn chồn hoặc lo lắng.', N'Viên nén', N'Cần kê đơn', 130000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0157', N'Kích ứng da hoặc niêm mạc (tại chỗ bôi/tiêm).', N'Viên nang mềm', N'Cần kê đơn', 460000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0158', N'Kích ứng da hoặc niêm mạc (tại chỗ bôi/tiêm).', N'Thuốc tiêm', N'Cần kê đơn', 70000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0159', N'Tiêu chảy hoặc phân lỏng tạm thời, nên dùng kèm thức ăn.', N'Thuốc mỡ', N'Cần kê đơn', 50000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0160', N'Mất cân bằng, đi lại loạng choạng sau khi dùng thuốc.', N'Viên nang mềm', N'Không cần kê đơn', 440000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0161', N'Không có tác dụng phụ đáng kể.', N'Thuốc mỡ', N'Không cần kê đơn', 190000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0162', N'Kích ứng da hoặc niêm mạc (tại chỗ bôi/tiêm).', N'Thuốc tiêm', N'Cần kê đơn', 80000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0163', N'Có thể gây vàng da, cần theo dõi chức năng gan.', N'Viên nén', N'Không cần kê đơn', 100000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0164', N'Thay đổi hành vi: kích động, bồn chồn hoặc lo lắng.', N'Viên nén', N'Cần kê đơn', 60000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0165', N'Mất cân bằng, đi lại loạng choạng sau khi dùng thuốc.', N'Dung dịch nhỏ mắt/tai', N'Không cần kê đơn', 130000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0166', N'Chóng mặt hoặc buồn nôn nhẹ.', N'Siro', N'Không cần kê đơn', 350000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0167', N'Tăng cường cảm giác thèm ăn hoặc ngược lại, biếng ăn thoáng qua.', N'Dung dịch nhỏ mắt/tai', N'Không cần kê đơn', 110000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0168', N'Nôn mửa hoặc sùi bọt mép .', N'Thuốc tiêm', N'Cần kê đơn', 110000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0169', N'Thay đổi hành vi: kích động, bồn chồn hoặc lo lắng.', N'Dung dịch nhỏ mắt/tai', N'Không cần kê đơn', 210000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0170', N'Uống nhiều nước và tiểu tiện nhiều hơn bình thường.', N'Thuốc bột pha dung dịch', N'Cần kê đơn', 160000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0171', N'Tăng cường cảm giác thèm ăn hoặc ngược lại, biếng ăn thoáng qua.', N'Thuốc bột pha dung dịch', N'Không cần kê đơn', 220000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0172', N'Mất cân bằng, đi lại loạng choạng sau khi dùng thuốc.', N'Viên nén (Tablet)', N'Không cần kê đơn', 280000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0173', N'Mất cân bằng, đi lại loạng choạng sau khi dùng thuốc.', N'Viên nang mềm (Softgel)', N'Không cần kê đơn', 160000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0174', N'Buồn ngủ nhẹ hoặc lừ đừ (phổ biến).', N'Viên nén (Tablet)', N'Cần kê đơn', 120000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0175', N'Kích ứng da hoặc niêm mạc (tại chỗ bôi/tiêm).', N'Viên nén (Tablet)', N'Cần kê đơn', 270000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0176', N'Không có tác dụng phụ đáng kể.', N'Viên nang mềm (Softgel)', N'Cần kê đơn', 140000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0177', N'Kích ứng da hoặc niêm mạc (tại chỗ bôi/tiêm).', N'Viên nén (Tablet)', N'Cần kê đơn', 50000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0178', N'Tăng cường cảm giác thèm ăn hoặc ngược lại, biếng ăn thoáng qua.', N'Viên nén', N'Không cần kê đơn', 450000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0179', N'Thay đổi hành vi: kích động, bồn chồn hoặc lo lắng.', N'Thuốc tiêm', N'Không cần kê đơn', 80000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0180', N'Có thể gây vàng da, cần theo dõi chức năng gan.', N'Viên nén (Tablet)', N'Không cần kê đơn', 170000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0181', N'Thay đổi hành vi: kích động, bồn chồn hoặc lo lắng.', N'Viên nang mềm (Softgel)', N'Không cần kê đơn', 440000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0182', N'Tiêu chảy hoặc phân lỏng tạm thời, nên dùng kèm thức ăn.', N'Viên nén', N'Cần kê đơn', 90000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0183', N'Có thể gây vàng da, cần theo dõi chức năng gan.', N'Viên nén', N'Cần kê đơn', 170000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0184', N'Mất cân bằng, đi lại loạng choạng sau khi dùng thuốc.', N'Viên nén', N'Cần kê đơn', 400000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0185', N'Tiêu chảy hoặc phân lỏng tạm thời, nên dùng kèm thức ăn.', N'Viên nén', N'Cần kê đơn', 270000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0186', N'Phản ứng dị ứng nhẹ (phát ban).', N'Viên nang mềm', N'Không cần kê đơn', 230000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0187', N'Mất cân bằng, đi lại loạng choạng sau khi dùng thuốc.', N'Thuốc tiêm', N'Cần kê đơn', 390000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0188', N'Nôn mửa hoặc sùi bọt mép .', N'Viên nén', N'Cần kê đơn', 110000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0189', N'Có thể gây vàng da, cần theo dõi chức năng gan.', N'Dung dịch nhỏ mắt/tai', N'Không cần kê đơn', 200000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0190', N'Kích ứng da hoặc niêm mạc (tại chỗ bôi/tiêm).', N'Thuốc bột pha dung dịch', N'Cần kê đơn', 280000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0191', N'Không có tác dụng phụ đáng kể.', N'Thuốc bột pha dung dịch', N'Cần kê đơn', 150000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0192', N'Kích ứng da hoặc niêm mạc (tại chỗ bôi/tiêm).', N'Thuốc bột pha dung dịch', N'Cần kê đơn', 230000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0193', N'Thay đổi hành vi: kích động, bồn chồn hoặc lo lắng.', N'Viên nén', N'Không cần kê đơn', 390000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0194', N'Mất cân bằng vi khuẩn đường ruột (dễ bị tiêu chảy).', N'Viên nang mềm', N'Cần kê đơn', 120000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0195', N'Buồn ngủ nhẹ hoặc lừ đừ (phổ biến).', N'Thuốc bột pha dung dịch', N'Không cần kê đơn', 70000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0196', N'Uống nhiều nước và tiểu tiện nhiều hơn bình thường.', N'Thuốc tiêm', N'Cần kê đơn', 370000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0197', N'Không có tác dụng phụ đáng kể.', N'Dung dịch nhỏ mắt/tai', N'Không cần kê đơn', 90000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0198', N'Uống nhiều nước và tiểu tiện nhiều hơn bình thường.', N'Thuốc bột pha dung dịch', N'Không cần kê đơn', 190000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0199', N'Tiêu chảy hoặc phân lỏng tạm thời, nên dùng kèm thức ăn.', N'Viên nén', N'Không cần kê đơn', 360000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0200', N'Kích ứng da hoặc niêm mạc (tại chỗ bôi/tiêm).', N'Thuốc tiêm', N'Cần kê đơn', 80000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0201', N'Tiêu chảy hoặc phân lỏng tạm thời, nên dùng kèm thức ăn.', N'Viên nén', N'Cần kê đơn', 270000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0202', N'Không có tác dụng phụ đáng kể.', N'Siro', N'Không cần kê đơn', 370000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0203', N'Có thể gây vàng da, cần theo dõi chức năng gan.', N'Viên nén', N'Cần kê đơn', 80000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0204', N'Run rẩy hoặc co giật cơ bắp (cần theo dõi nghiêm ngặt).', N'Viên nang mềm', N'Không cần kê đơn', 160000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0205', N'Kích ứng da hoặc niêm mạc (tại chỗ bôi/tiêm).', N'Siro', N'Không cần kê đơn', 440000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0206', N'Kích ứng da hoặc ngứa nhẹ tại chỗ bôi.', N'Thuốc mỡ', N'Không cần kê đơn', 290000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0207', N'Mất cân bằng, đi lại loạng choạng sau khi dùng thuốc.', N'Dung dịch nhỏ mắt/tai', N'Không cần kê đơn', 230000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0208', N'Không có tác dụng phụ đáng kể.', N'Viên nang mềm', N'Không cần kê đơn', 350000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0209', N'Thay đổi hành vi: kích động, bồn chồn hoặc lo lắng.', N'Dung dịch nhỏ mắt/tai', N'Không cần kê đơn', 200000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0210', N'Tiêu chảy hoặc phân lỏng tạm thời, nên dùng kèm thức ăn.', N'Viên nang mềm', N'Không cần kê đơn', 90000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0211', N'Tăng cường cảm giác thèm ăn hoặc ngược lại, biếng ăn thoáng qua.', N'Dung dịch nhỏ mắt/tai', N'Không cần kê đơn', 410000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0212', N'Thay đổi hành vi: kích động, bồn chồn hoặc lo lắng.', N'Viên nén', N'Không cần kê đơn', 120000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0213', N'Không có tác dụng phụ đáng kể.', N'Dung dịch nhỏ mắt/tai', N'Cần kê đơn', 250000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0214', N'Run rẩy hoặc co giật cơ bắp (cần theo dõi nghiêm ngặt).', N'Viên nang mềm', N'Không cần kê đơn', 480000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0215', N'Buồn ngủ nhẹ hoặc lừ đừ (phổ biến).', N'Siro', N'Cần kê đơn', 220000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0216', N'Có thể gây vàng da, cần theo dõi chức năng gan.', N'Thuốc bột pha dung dịch', N'Không cần kê đơn', 210000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0217', N'Buồn ngủ nhẹ hoặc lừ đừ (phổ biến).', N'Siro', N'Không cần kê đơn', 500000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0218', N'Mất cân bằng, đi lại loạng choạng sau khi dùng thuốc.', N'Dung dịch nhỏ mắt/tai', N'Không cần kê đơn', 80000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0219', N'Buồn nôn hoặc nôn mửa thoáng qua.', N'Thuốc tiêm', N'Cần kê đơn', 280000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0220', N'Run rẩy hoặc co giật cơ bắp (cần theo dõi nghiêm ngặt).', N'Viên nén', N'Cần kê đơn', 190000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0221', N'Kích ứng da hoặc niêm mạc (tại chỗ bôi/tiêm).', N'Viên nén', N'Cần kê đơn', 200000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0222', N'Mất cân bằng, đi lại loạng choạng sau khi dùng thuốc.', N'Viên nang mềm', N'Không cần kê đơn', 140000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0223', N'Tăng cường cảm giác thèm ăn hoặc ngược lại, biếng ăn thoáng qua.', N'Siro', N'Không cần kê đơn', 440000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0224', N'Nôn mửa hoặc sùi bọt mép .', N'Viên nang mềm', N'Không cần kê đơn', 50000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0225', N'Tiêu chảy hoặc phân lỏng tạm thời, nên dùng kèm thức ăn.', N'Thuốc tiêm', N'Cần kê đơn', 190000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0226', N'Kích ứng da hoặc niêm mạc (tại chỗ bôi/tiêm).', N'Thuốc tiêm', N'Cần kê đơn', 130000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0227', N'Nôn mửa hoặc sùi bọt mép .', N'Thuốc mỡ', N'Không cần kê đơn', 210000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0228', N'Có thể gây vàng da, cần theo dõi chức năng gan.', N'Thuốc tiêm', N'Cần kê đơn', 280000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0229', N'Tăng cường cảm giác thèm ăn hoặc ngược lại, biếng ăn thoáng qua.', N'Viên nén', N'Không cần kê đơn', 430000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0230', N'Tiêu chảy hoặc phân lỏng tạm thời, nên dùng kèm thức ăn.', N'Siro', N'Không cần kê đơn', 210000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0231', N'Kích ứng da hoặc niêm mạc (tại chỗ bôi/tiêm).', N'Dung dịch nhỏ mắt/tai', N'Không cần kê đơn', 120000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0232', N'Mất cân bằng, đi lại loạng choạng sau khi dùng thuốc.', N'Thuốc mỡ', N'Không cần kê đơn', 490000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0233', N'Uống nhiều nước và tiểu tiện nhiều hơn bình thường.', N'Siro', N'Cần kê đơn', 130000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0234', N'Uống nhiều nước và tiểu tiện nhiều hơn bình thường.', N'Thuốc bột pha dung dịch', N'Không cần kê đơn', 80000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0235', N'Buồn ngủ nhẹ hoặc lừ đừ (phổ biến).', N'Viên nang mềm', N'Không cần kê đơn', 350000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0236', N'Không có tác dụng phụ đáng kể.', N'Viên nang mềm', N'Không cần kê đơn', 160000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0237', N'Tiêu chảy hoặc phân lỏng tạm thời, nên dùng kèm thức ăn.', N'Viên nang mềm', N'Không cần kê đơn', 90000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0238', N'Buồn ngủ nhẹ hoặc lừ đừ (phổ biến).', N'Thuốc mỡ', N'Cần kê đơn', 450000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0239', N'Nôn mửa hoặc sùi bọt mép .', N'Viên nang mềm', N'Cần kê đơn', 190000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0240', N'Có thể gây vàng da, cần theo dõi chức năng gan.', N'Thuốc mỡ', N'Cần kê đơn', 270000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0241', N'Kích ứng da hoặc niêm mạc (tại chỗ bôi/tiêm).', N'Viên nang mềm', N'Không cần kê đơn', 440000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0242', N'Có thể gây vàng da, cần theo dõi chức năng gan.', N'Thuốc bột pha dung dịch', N'Cần kê đơn', 190000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0243', N'Thay đổi hành vi: kích động, bồn chồn hoặc lo lắng.', N'Viên nang mềm', N'Không cần kê đơn', 210000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0244', N'Có thể gây vàng da, cần theo dõi chức năng gan.', N'Viên nang mềm', N'Không cần kê đơn', 300000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0245', N'Thay đổi hành vi: kích động, bồn chồn hoặc lo lắng.', N'Thuốc tiêm', N'Cần kê đơn', 70000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0246', N'Khó thở nhẹ, thở nhanh.', N'Viên nang mềm', N'Cần kê đơn', 200000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0247', N'Uống nhiều nước và tiểu tiện nhiều hơn bình thường.', N'Viên nén', N'Không cần kê đơn', 180000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0248', N'Kích ứng da hoặc niêm mạc (tại chỗ bôi/tiêm).', N'Thuốc tiêm', N'Cần kê đơn', 70000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0249', N'Khó thở nhẹ, thở nhanh.', N'Viên nén', N'Cần kê đơn', 250000.00);
INSERT INTO THUOC (MaThuoc, TacDungPhu, DangBaoChe, LoaiThuoc, DonGia) VALUES (N'MH0250', N'Kích ứng da hoặc niêm mạc (tại chỗ bôi/tiêm).', N'Thuốc mỡ', N'Không cần kê đơn', 110000.00);