USE HAPPYPET
GO


INSERT INTO VACCINE (MaVaccine, ChongChiDinh, DonGia) VALUES (N'MH0251', N'Thú cưng đang mang thai (tránh vaccine sống giảm độc lực).', 350000.00);
INSERT INTO VACCINE (MaVaccine, ChongChiDinh, DonGia) VALUES (N'MH0252', N'Đang được điều trị bằng Corticosteroid hoặc thuốc ức chế miễn dịch.', 330000.00);
INSERT INTO VACCINE (MaVaccine, ChongChiDinh, DonGia) VALUES (N'MH0253', N'Đang được điều trị bằng Corticosteroid hoặc thuốc ức chế miễn dịch.', 410000.00);
INSERT INTO VACCINE (MaVaccine, ChongChiDinh, DonGia) VALUES (N'MH0254', N'Thiếu máu hoặc có chỉ số máu bất thường.', 270000.00);
INSERT INTO VACCINE (MaVaccine, ChongChiDinh, DonGia) VALUES (N'MH0255', N'Thú cưng dưới 6 tuần tuổi (hoặc theo hướng dẫn của nhà sản xuất).', 400000.00);
INSERT INTO VACCINE (MaVaccine, ChongChiDinh, DonGia) VALUES (N'MH0256', N'Bị nhiễm ký sinh trùng nặng (giun, sán) chưa được điều trị.', 590000.00);
INSERT INTO VACCINE (MaVaccine, ChongChiDinh, DonGia) VALUES (N'MH0257', N'Đang được điều trị bằng Corticosteroid hoặc thuốc ức chế miễn dịch.', 330000.00);
INSERT INTO VACCINE (MaVaccine, ChongChiDinh, DonGia) VALUES (N'MH0258', N'Đang được điều trị bằng Corticosteroid hoặc thuốc ức chế miễn dịch.', 460000.00);
INSERT INTO VACCINE (MaVaccine, ChongChiDinh, DonGia) VALUES (N'MH0259', N'Bị nhiễm ký sinh trùng nặng (giun, sán) chưa được điều trị.', 490000.00);
INSERT INTO VACCINE (MaVaccine, ChongChiDinh, DonGia) VALUES (N'MH0260', N'Bị rối loạn đông máu hoặc đang dùng thuốc chống đông.', 200000.00);
INSERT INTO VACCINE (MaVaccine, ChongChiDinh, DonGia) VALUES (N'MH0261', N'Có tiền sử bệnh tự miễn (ví dụ: Lupus).', 520000.00);
INSERT INTO VACCINE (MaVaccine, ChongChiDinh, DonGia) VALUES (N'MH0262', N'Thú cưng bị suy giảm miễn dịch bẩm sinh hoặc mắc phải.', 600000.00);
INSERT INTO VACCINE (MaVaccine, ChongChiDinh, DonGia) VALUES (N'MH0263', N'Thú cưng đang bị sốt hoặc có dấu hiệu bệnh lý cấp tính.', 640000.00);
INSERT INTO VACCINE (MaVaccine, ChongChiDinh, DonGia) VALUES (N'MH0264', N'Đang được điều trị bằng Corticosteroid hoặc thuốc ức chế miễn dịch.', 380000.00);
INSERT INTO VACCINE (MaVaccine, ChongChiDinh, DonGia) VALUES (N'MH0265', N'Bị rối loạn đông máu hoặc đang dùng thuốc chống đông.', 230000.00);
INSERT INTO VACCINE (MaVaccine, ChongChiDinh, DonGia) VALUES (N'MH0266', N'Thú cưng vừa trải qua phẫu thuật hoặc stress nặng.', 720000.00);
INSERT INTO VACCINE (MaVaccine, ChongChiDinh, DonGia) VALUES (N'MH0267', N'Thú cưng bị suy giảm miễn dịch bẩm sinh hoặc mắc phải.', 210000.00);
INSERT INTO VACCINE (MaVaccine, ChongChiDinh, DonGia) VALUES (N'MH0268', N'Bị nhiễm ký sinh trùng nặng (giun, sán) chưa được điều trị.', 390000.00);
INSERT INTO VACCINE (MaVaccine, ChongChiDinh, DonGia) VALUES (N'MH0269', N'Có tiền sử phản ứng dị ứng nghiêm trọng (quá mẫn) với vaccine trước đó.', 360000.00);
INSERT INTO VACCINE (MaVaccine, ChongChiDinh, DonGia) VALUES (N'MH0270', N'Thú cưng quá già hoặc mắc bệnh mãn tính nghiêm trọng (tim, thận).', 780000.00);
INSERT INTO VACCINE (MaVaccine, ChongChiDinh, DonGia) VALUES (N'MH0271', N'Thú cưng bị suy giảm miễn dịch bẩm sinh hoặc mắc phải.', 430000.00);
INSERT INTO VACCINE (MaVaccine, ChongChiDinh, DonGia) VALUES (N'MH0272', N'Chưa xổ giun đầy đủ trước khi tiêm.', 720000.00);
INSERT INTO VACCINE (MaVaccine, ChongChiDinh, DonGia) VALUES (N'MH0273', N'Chưa xổ giun đầy đủ trước khi tiêm.', 790000.00);
INSERT INTO VACCINE (MaVaccine, ChongChiDinh, DonGia) VALUES (N'MH0274', N'Chưa xổ giun đầy đủ trước khi tiêm.', 470000.00);
INSERT INTO VACCINE (MaVaccine, ChongChiDinh, DonGia) VALUES (N'MH0275', N'Đang được điều trị bằng Corticosteroid hoặc thuốc ức chế miễn dịch.', 410000.00);
INSERT INTO VACCINE (MaVaccine, ChongChiDinh, DonGia) VALUES (N'MH0276', N'Thú cưng dưới 6 tuần tuổi (hoặc theo hướng dẫn của nhà sản xuất).', 450000.00);
INSERT INTO VACCINE (MaVaccine, ChongChiDinh, DonGia) VALUES (N'MH0277', N'Tiếp xúc với thú cưng mắc bệnh truyền nhiễm trong vòng 7 ngày.', 450000.00);
INSERT INTO VACCINE (MaVaccine, ChongChiDinh, DonGia) VALUES (N'MH0278', N'Thú cưng đang bị sốt hoặc có dấu hiệu bệnh lý cấp tính.', 410000.00);
INSERT INTO VACCINE (MaVaccine, ChongChiDinh, DonGia) VALUES (N'MH0279', N'Thú cưng đang bị sốt hoặc có dấu hiệu bệnh lý cấp tính.', 440000.00);
INSERT INTO VACCINE (MaVaccine, ChongChiDinh, DonGia) VALUES (N'MH0280', N'Thú cưng bị suy giảm miễn dịch bẩm sinh hoặc mắc phải.', 330000.00);
INSERT INTO VACCINE (MaVaccine, ChongChiDinh, DonGia) VALUES (N'MH0281', N'Đã tiêm một loại vaccine khác trong vòng 10-14 ngày gần nhất.', 370000.00);
INSERT INTO VACCINE (MaVaccine, ChongChiDinh, DonGia) VALUES (N'MH0282', N'Có tiền sử phản ứng dị ứng nghiêm trọng (quá mẫn) với vaccine trước đó.', 350000.00);
INSERT INTO VACCINE (MaVaccine, ChongChiDinh, DonGia) VALUES (N'MH0283', N'Thú cưng quá già hoặc mắc bệnh mãn tính nghiêm trọng (tim, thận).', 430000.00);
INSERT INTO VACCINE (MaVaccine, ChongChiDinh, DonGia) VALUES (N'MH0284', N'Thú cưng đang mang thai (tránh vaccine sống giảm độc lực).', 340000.00);
INSERT INTO VACCINE (MaVaccine, ChongChiDinh, DonGia) VALUES (N'MH0285', N'Tiếp xúc với thú cưng mắc bệnh truyền nhiễm trong vòng 7 ngày.', 210000.00);
INSERT INTO VACCINE (MaVaccine, ChongChiDinh, DonGia) VALUES (N'MH0286', N'Thú cưng vừa trải qua phẫu thuật hoặc stress nặng.', 510000.00);
INSERT INTO VACCINE (MaVaccine, ChongChiDinh, DonGia) VALUES (N'MH0287', N'Thú cưng đang mang thai (tránh vaccine sống giảm độc lực).', 300000.00);
INSERT INTO VACCINE (MaVaccine, ChongChiDinh, DonGia) VALUES (N'MH0288', N'Bị bệnh ngoài da, áp xe hoặc vết thương hở tại vị trí tiêm.', 620000.00);
INSERT INTO VACCINE (MaVaccine, ChongChiDinh, DonGia) VALUES (N'MH0289', N'Đã tiêm một loại vaccine khác trong vòng 10-14 ngày gần nhất.', 450000.00);
INSERT INTO VACCINE (MaVaccine, ChongChiDinh, DonGia) VALUES (N'MH0290', N'Tiếp xúc với thú cưng mắc bệnh truyền nhiễm trong vòng 7 ngày.', 240000.00);
INSERT INTO VACCINE (MaVaccine, ChongChiDinh, DonGia) VALUES (N'MH0291', N'Sự hiện diện của kháng thể mẹ truyền (đối với thú non).', 710000.00);
INSERT INTO VACCINE (MaVaccine, ChongChiDinh, DonGia) VALUES (N'MH0292', N'Chưa xổ giun đầy đủ trước khi tiêm.', 350000.00);
INSERT INTO VACCINE (MaVaccine, ChongChiDinh, DonGia) VALUES (N'MH0293', N'Thú cưng vừa trải qua phẫu thuật hoặc stress nặng.', 420000.00);
INSERT INTO VACCINE (MaVaccine, ChongChiDinh, DonGia) VALUES (N'MH0294', N'Bị rối loạn đông máu hoặc đang dùng thuốc chống đông.', 760000.00);
INSERT INTO VACCINE (MaVaccine, ChongChiDinh, DonGia) VALUES (N'MH0295', N'Thú cưng bị suy giảm miễn dịch bẩm sinh hoặc mắc phải.', 540000.00);
INSERT INTO VACCINE (MaVaccine, ChongChiDinh, DonGia) VALUES (N'MH0296', N'Thiếu máu hoặc có chỉ số máu bất thường.', 480000.00);
INSERT INTO VACCINE (MaVaccine, ChongChiDinh, DonGia) VALUES (N'MH0297', N'Chưa xổ giun đầy đủ trước khi tiêm.', 560000.00);
INSERT INTO VACCINE (MaVaccine, ChongChiDinh, DonGia) VALUES (N'MH0298', N'Bị bệnh ngoài da, áp xe hoặc vết thương hở tại vị trí tiêm.', 270000.00);
INSERT INTO VACCINE (MaVaccine, ChongChiDinh, DonGia) VALUES (N'MH0299', N'Thiếu máu hoặc có chỉ số máu bất thường.', 480000.00);
INSERT INTO VACCINE (MaVaccine, ChongChiDinh, DonGia) VALUES (N'MH0300', N'Có tiền sử phản ứng dị ứng nghiêm trọng (quá mẫn) với vaccine trước đó.', 360000.00);
INSERT INTO VACCINE (MaVaccine, ChongChiDinh, DonGia) VALUES (N'MH0301', N'Chưa xổ giun đầy đủ trước khi tiêm.', 370000.00);
INSERT INTO VACCINE (MaVaccine, ChongChiDinh, DonGia) VALUES (N'MH0302', N'Nhiễm virus tiềm ẩn (ví dụ: FIP, FIV, FeLV chưa được kiểm soát).', 510000.00);
INSERT INTO VACCINE (MaVaccine, ChongChiDinh, DonGia) VALUES (N'MH0303', N'Thiếu máu hoặc có chỉ số máu bất thường.', 680000.00);
INSERT INTO VACCINE (MaVaccine, ChongChiDinh, DonGia) VALUES (N'MH0304', N'Sự hiện diện của kháng thể mẹ truyền (đối với thú non).', 600000.00);
INSERT INTO VACCINE (MaVaccine, ChongChiDinh, DonGia) VALUES (N'MH0305', N'Bị rối loạn đông máu hoặc đang dùng thuốc chống đông.', 270000.00);
INSERT INTO VACCINE (MaVaccine, ChongChiDinh, DonGia) VALUES (N'MH0306', N'Bị nhiễm ký sinh trùng nặng (giun, sán) chưa được điều trị.', 480000.00);
INSERT INTO VACCINE (MaVaccine, ChongChiDinh, DonGia) VALUES (N'MH0307', N'Có tiền sử phản ứng dị ứng nghiêm trọng (quá mẫn) với vaccine trước đó.', 690000.00);
INSERT INTO VACCINE (MaVaccine, ChongChiDinh, DonGia) VALUES (N'MH0308', N'Thú cưng đang bị sốt hoặc có dấu hiệu bệnh lý cấp tính.', 770000.00);
INSERT INTO VACCINE (MaVaccine, ChongChiDinh, DonGia) VALUES (N'MH0309', N'Có tiền sử bệnh tự miễn (ví dụ: Lupus).', 280000.00);
INSERT INTO VACCINE (MaVaccine, ChongChiDinh, DonGia) VALUES (N'MH0310', N'Bị bệnh ngoài da, áp xe hoặc vết thương hở tại vị trí tiêm.', 250000.00);
INSERT INTO VACCINE (MaVaccine, ChongChiDinh, DonGia) VALUES (N'MH0311', N'Bị rối loạn đông máu hoặc đang dùng thuốc chống đông.', 250000.00);
INSERT INTO VACCINE (MaVaccine, ChongChiDinh, DonGia) VALUES (N'MH0312', N'Thú cưng đang mang thai (tránh vaccine sống giảm độc lực).', 290000.00);
INSERT INTO VACCINE (MaVaccine, ChongChiDinh, DonGia) VALUES (N'MH0313', N'Đang được điều trị bằng Corticosteroid hoặc thuốc ức chế miễn dịch.', 340000.00);
INSERT INTO VACCINE (MaVaccine, ChongChiDinh, DonGia) VALUES (N'MH0314', N'Thú cưng đang trong thời kỳ cho con bú.', 310000.00);
INSERT INTO VACCINE (MaVaccine, ChongChiDinh, DonGia) VALUES (N'MH0315', N'Đã tiêm một loại vaccine khác trong vòng 10-14 ngày gần nhất.', 770000.00);
INSERT INTO VACCINE (MaVaccine, ChongChiDinh, DonGia) VALUES (N'MH0316', N'Thiếu máu hoặc có chỉ số máu bất thường.', 610000.00);
INSERT INTO VACCINE (MaVaccine, ChongChiDinh, DonGia) VALUES (N'MH0317', N'Đang được điều trị bằng Corticosteroid hoặc thuốc ức chế miễn dịch.', 230000.00);
INSERT INTO VACCINE (MaVaccine, ChongChiDinh, DonGia) VALUES (N'MH0318', N'Bị bệnh ngoài da, áp xe hoặc vết thương hở tại vị trí tiêm.', 520000.00);
INSERT INTO VACCINE (MaVaccine, ChongChiDinh, DonGia) VALUES (N'MH0319', N'Thú cưng quá già hoặc mắc bệnh mãn tính nghiêm trọng (tim, thận).', 570000.00);
INSERT INTO VACCINE (MaVaccine, ChongChiDinh, DonGia) VALUES (N'MH0320', N'Có tiền sử bệnh tự miễn (ví dụ: Lupus).', 480000.00);
INSERT INTO VACCINE (MaVaccine, ChongChiDinh, DonGia) VALUES (N'MH0321', N'Tiếp xúc với thú cưng mắc bệnh truyền nhiễm trong vòng 7 ngày.', 600000.00);
INSERT INTO VACCINE (MaVaccine, ChongChiDinh, DonGia) VALUES (N'MH0322', N'Thú cưng quá già hoặc mắc bệnh mãn tính nghiêm trọng (tim, thận).', 490000.00);
INSERT INTO VACCINE (MaVaccine, ChongChiDinh, DonGia) VALUES (N'MH0323', N'Có tiền sử bệnh tự miễn (ví dụ: Lupus).', 450000.00);
INSERT INTO VACCINE (MaVaccine, ChongChiDinh, DonGia) VALUES (N'MH0324', N'Bị bệnh ngoài da, áp xe hoặc vết thương hở tại vị trí tiêm.', 510000.00);
INSERT INTO VACCINE (MaVaccine, ChongChiDinh, DonGia) VALUES (N'MH0325', N'Thú cưng dưới 6 tuần tuổi (hoặc theo hướng dẫn của nhà sản xuất).', 460000.00);
INSERT INTO VACCINE (MaVaccine, ChongChiDinh, DonGia) VALUES (N'MH0326', N'Có tiền sử bệnh tự miễn (ví dụ: Lupus).', 670000.00);
INSERT INTO VACCINE (MaVaccine, ChongChiDinh, DonGia) VALUES (N'MH0327', N'Có tiền sử bệnh tự miễn (ví dụ: Lupus).', 540000.00);
INSERT INTO VACCINE (MaVaccine, ChongChiDinh, DonGia) VALUES (N'MH0328', N'Thú cưng đang trong thời kỳ cho con bú.', 380000.00);
INSERT INTO VACCINE (MaVaccine, ChongChiDinh, DonGia) VALUES (N'MH0329', N'Thú cưng đang mang thai (tránh vaccine sống giảm độc lực).', 490000.00);
INSERT INTO VACCINE (MaVaccine, ChongChiDinh, DonGia) VALUES (N'MH0330', N'Thú cưng bị suy dinh dưỡng nặng hoặc quá yếu.', 730000.00);
INSERT INTO VACCINE (MaVaccine, ChongChiDinh, DonGia) VALUES (N'MH0331', N'Bị bệnh ngoài da, áp xe hoặc vết thương hở tại vị trí tiêm.', 780000.00);
INSERT INTO VACCINE (MaVaccine, ChongChiDinh, DonGia) VALUES (N'MH0332', N'Bị bệnh ngoài da, áp xe hoặc vết thương hở tại vị trí tiêm.', 680000.00);
INSERT INTO VACCINE (MaVaccine, ChongChiDinh, DonGia) VALUES (N'MH0333', N'Thú cưng bị suy dinh dưỡng nặng hoặc quá yếu.', 720000.00);
INSERT INTO VACCINE (MaVaccine, ChongChiDinh, DonGia) VALUES (N'MH0334', N'Thú cưng vừa trải qua phẫu thuật hoặc stress nặng.', 470000.00);
INSERT INTO VACCINE (MaVaccine, ChongChiDinh, DonGia) VALUES (N'MH0335', N'Tiếp xúc với thú cưng mắc bệnh truyền nhiễm trong vòng 7 ngày.', 780000.00);
INSERT INTO VACCINE (MaVaccine, ChongChiDinh, DonGia) VALUES (N'MH0336', N'Thú cưng dưới 6 tuần tuổi (hoặc theo hướng dẫn của nhà sản xuất).', 450000.00);
INSERT INTO VACCINE (MaVaccine, ChongChiDinh, DonGia) VALUES (N'MH0337', N'Sự hiện diện của kháng thể mẹ truyền (đối với thú non).', 300000.00);
INSERT INTO VACCINE (MaVaccine, ChongChiDinh, DonGia) VALUES (N'MH0338', N'Thú cưng bị suy giảm miễn dịch bẩm sinh hoặc mắc phải.', 680000.00);
INSERT INTO VACCINE (MaVaccine, ChongChiDinh, DonGia) VALUES (N'MH0339', N'Đã tiêm một loại vaccine khác trong vòng 10-14 ngày gần nhất.', 770000.00);
INSERT INTO VACCINE (MaVaccine, ChongChiDinh, DonGia) VALUES (N'MH0340', N'Thú cưng bị suy giảm miễn dịch bẩm sinh hoặc mắc phải.', 270000.00);
INSERT INTO VACCINE (MaVaccine, ChongChiDinh, DonGia) VALUES (N'MH0341', N'Bị bệnh ngoài da, áp xe hoặc vết thương hở tại vị trí tiêm.', 210000.00);
INSERT INTO VACCINE (MaVaccine, ChongChiDinh, DonGia) VALUES (N'MH0342', N'Đã tiêm một loại vaccine khác trong vòng 10-14 ngày gần nhất.', 520000.00);
INSERT INTO VACCINE (MaVaccine, ChongChiDinh, DonGia) VALUES (N'MH0343', N'Có tiền sử phản ứng dị ứng nghiêm trọng (quá mẫn) với vaccine trước đó.', 400000.00);
INSERT INTO VACCINE (MaVaccine, ChongChiDinh, DonGia) VALUES (N'MH0344', N'Thú cưng dưới 6 tuần tuổi (hoặc theo hướng dẫn của nhà sản xuất).', 490000.00);
INSERT INTO VACCINE (MaVaccine, ChongChiDinh, DonGia) VALUES (N'MH0345', N'Sự hiện diện của kháng thể mẹ truyền (đối với thú non).', 490000.00);
INSERT INTO VACCINE (MaVaccine, ChongChiDinh, DonGia) VALUES (N'MH0346', N'Thú cưng bị suy dinh dưỡng nặng hoặc quá yếu.', 590000.00);
INSERT INTO VACCINE (MaVaccine, ChongChiDinh, DonGia) VALUES (N'MH0347', N'Chưa xổ giun đầy đủ trước khi tiêm.', 680000.00);
INSERT INTO VACCINE (MaVaccine, ChongChiDinh, DonGia) VALUES (N'MH0348', N'Thú cưng đang mang thai (tránh vaccine sống giảm độc lực).', 290000.00);
INSERT INTO VACCINE (MaVaccine, ChongChiDinh, DonGia) VALUES (N'MH0349', N'Chưa xổ giun đầy đủ trước khi tiêm.', 580000.00);
INSERT INTO VACCINE (MaVaccine, ChongChiDinh, DonGia) VALUES (N'MH0350', N'Thú cưng đang bị sốt hoặc có dấu hiệu bệnh lý cấp tính.', 650000.00);